function formats = defaultFormats()
%DEFAULTFORMATS Return default speaker format presets.
%
% Project:
%   Immersive Metering Tool
%
% Supported formats:
%   mono
%   stereo
%   4.0 / Quad
%   5.1
%   7.1
%   7.1.2
%   7.1.4
%
% Channel-order note:
%   These are practical default mappings. WAV channel order is not always
%   guaranteed, so the user should still be allowed to edit the channel map.

    formats = struct([]);

    formats(end + 1) = makeFormat( ...
        "mono", ...
        ["M"], ...
        [0], ...
        [0], ...
        ["Center"], ...
        [false]);

    formats(end + 1) = makeFormat( ...
        "stereo", ...
        ["L", "R"], ...
        [-30, 30], ...
        [0, 0], ...
        ["Front", "Front"], ...
        [false, false]);

    formats(end + 1) = makeFormat( ...
        "4.0", ...
        ["L", "R", "Ls", "Rs"], ...
        [-30, 30, -110, 110], ...
        [0, 0, 0, 0], ...
        ["Front", "Front", "Side", "Side"], ...
        [false, false, false, false]);

    formats(end + 1) = makeFormat( ...
        "5.1", ...
        ["L", "R", "C", "LFE", "Ls", "Rs"], ...
        [-30, 30, 0, 0, -110, 110], ...
        [0, 0, 0, 0, 0, 0], ...
        ["Front", "Front", "Front", "LFE", "Side", "Side"], ...
        [false, false, false, true, false, false]);

    formats(end + 1) = makeFormat( ...
        "7.1", ...
        ["L", "R", "C", "LFE", "Ls", "Rs", "Lrs", "Rrs"], ...
        [-30, 30, 0, 0, -90, 90, -135, 135], ...
        [0, 0, 0, 0, 0, 0, 0, 0], ...
        ["Front", "Front", "Front", "LFE", "Side", "Side", "Rear", "Rear"], ...
        [false, false, false, true, false, false, false, false]);

    formats(end + 1) = makeFormat( ...
        "7.1.2", ...
        ["L", "R", "C", "LFE", "Ls", "Rs", "Lrs", "Rrs", "Ltm", "Rtm"], ...
        [-30, 30, 0, 0, -90, 90, -135, 135, -90, 90], ...
        [0, 0, 0, 0, 0, 0, 0, 0, 80, 80], ...
        ["Front", "Front", "Front", "LFE", "Side", "Side", "Rear", "Rear", "HeightMiddle", "HeightMiddle"], ...
        [false, false, false, true, false, false, false, false, false, false]);

    formats(end + 1) = makeFormat( ...
        "7.1.4", ...
        ["L", "R", "C", "LFE", "Ls", "Rs", "Lrs", "Rrs", "Ltf", "Rtf", "Ltr", "Rtr"], ...
        [-30, 30, 0, 0, -90, 90, -135, 135, -45, 45, -135, 135], ...
        [0, 0, 0, 0, 0, 0, 0, 0, 45, 45, 45, 45], ...
        ["Front", "Front", "Front", "LFE", "Side", "Side", "Rear", "Rear", "HeightFront", "HeightFront", "HeightRear", "HeightRear"], ...
        [false, false, false, true, false, false, false, false, false, false, false, false]);
end

function fmt = makeFormat(name, labels, azimuthDeg, elevationDeg, group, isLFE)
%MAKEFORMAT Build one format preset struct.

    labels = string(labels(:));
    azimuthDeg = double(azimuthDeg(:));
    elevationDeg = double(elevationDeg(:));
    group = string(group(:));
    isLFE = logical(isLFE(:));

    channelCount = numel(labels);

    if numel(azimuthDeg) ~= channelCount || ...
            numel(elevationDeg) ~= channelCount || ...
            numel(group) ~= channelCount || ...
            numel(isLFE) ~= channelCount
        error("defaultFormats:InvalidPreset", ...
            "Format preset %s has mismatched field lengths.", string(name));
    end

    FileChannel = (1:channelCount).';
    SpeakerLabel = labels;
    Group = group;
    IsLFE = isLFE;

    IncludeInLoudness = ~IsLFE;
    IncludeInSpatial = ~IsLFE;

    LoudnessWeight = ones(channelCount, 1);
    LoudnessWeight(IsLFE) = 0;

    AzimuthDeg = azimuthDeg;
    ElevationDeg = elevationDeg;

    speakerTable = table( ...
        FileChannel, ...
        SpeakerLabel, ...
        Group, ...
        IsLFE, ...
        IncludeInLoudness, ...
        IncludeInSpatial, ...
        LoudnessWeight, ...
        AzimuthDeg, ...
        ElevationDeg);

    fmt = struct();

    fmt.Name = string(name);
    fmt.ChannelCount = channelCount;
    fmt.SpeakerTable = speakerTable;

    % Extra fields for compatibility with older helper functions.
    fmt.FileChannel = FileChannel;
    fmt.SpeakerLabel = SpeakerLabel;
    fmt.Labels = SpeakerLabel;
    fmt.Group = Group;
    fmt.IsLFE = IsLFE;
    fmt.IncludeInLoudness = IncludeInLoudness;
    fmt.IncludeInSpatial = IncludeInSpatial;
    fmt.LoudnessWeight = LoudnessWeight;
    fmt.AzimuthDeg = AzimuthDeg;
    fmt.ElevationDeg = ElevationDeg;
end